/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CategoriaControlller;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import controlador.EventsController;
import controlador.ProductoController;
import controlador.HistorialController;
import javax.swing.JInternalFrame;
import javax.swing.table.DefaultTableModel;
import modelo.Usuario;
import modelo.Categoria;
import modelo.Historial;

/**
 *
 * @author r.kumbara
 */
public class frmMain extends javax.swing.JFrame {

    int x = 350;
    EventsController view;
    private JInternalFrame activeFrame;
    static Usuario user;
    ProductoController productoController = new ProductoController();
    CategoriaControlller categoriaController = new CategoriaControlller();
    HistorialController historialController = new HistorialController();

    public frmMain() {
        initComponents();
        muestraCategoria();
        this.setLocationRelativeTo(null);
        view = new EventsController(this);
        closeAllFrames();
        panelCategorias.setVisible(false);
        panelProveedores.setVisible(false);
        panelListadoUsuarios.setVisible(false);
        if (user.getId_tipo() == 1) {
            showBossPanels();
        }
        llevarCbTipoProducto();
        tablaProducto();

    }

    void showBossPanels() {
        panelCategorias.setVisible(true);
        panelProveedores.setVisible(true);
        panelListadoUsuarios.setVisible(true);

    }

    void closeAllFrames() {
        frmProductos.setVisible(false);
        frmProveedores.setVisible(false);
        frmHistorial.setVisible(false);
        frmClasificacion.setVisible(false);
        frmListadoUsuarios.setVisible(false);
        frmCategorias.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        slideBar = new javax.swing.JPanel();
        panelCategorias = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        panelProductos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelProveedores = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelDetalle = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panelClasificacion = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panelListadoUsuarios = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        slideIcon = new javax.swing.JLabel();
        frmCategorias = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        btnCerrarCategoria = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaCategoria = new javax.swing.JTable();
        Actualizar = new javax.swing.JButton();
        frmListadoUsuarios = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        btnCerrarListado = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        frmClasificacion = new javax.swing.JInternalFrame();
        jPanel5 = new javax.swing.JPanel();
        btnCerrarClasificacion = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        cbTipoProducto = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableClasificacionProducto = new javax.swing.JTable();
        frmProductos = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        btnIngProduc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        btnModProduc = new javax.swing.JButton();
        btnElimProduc = new javax.swing.JButton();
        btnCerrarRegistro = new javax.swing.JButton();
        TablaProducto = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        frmProveedores = new javax.swing.JInternalFrame();
        jPanel6 = new javax.swing.JPanel();
        btnCerrarProveedores = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        frmHistorial = new javax.swing.JInternalFrame();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHistorialProducto = new javax.swing.JTable();
        btnCerrarHistorial = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        btnBuscarHistorial = new javax.swing.JButton();
        txtidHistorial = new javax.swing.JTextField();
        fontImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(1230, 720));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 625));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slideBar.setBackground(new java.awt.Color(54, 70, 78));
        slideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCategorias.setBackground(new java.awt.Color(54, 70, 78));
        panelCategorias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-increase-23.png"))); // NOI18N
        panelCategorias.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 40, 30));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Mantenimiento de Categorias");
        panelCategorias.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 270, 20));

        slideBar.add(panelCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 350, 40));

        panelProductos.setBackground(new java.awt.Color(54, 70, 78));
        panelProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-home-page-23.png"))); // NOI18N
        panelProductos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 40, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mantenimiento de Productos");
        panelProductos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 270, 20));

        slideBar.add(panelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 350, 40));

        panelProveedores.setBackground(new java.awt.Color(54, 70, 78));
        panelProveedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-male-user-23.png"))); // NOI18N
        panelProveedores.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 40, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mantenimiento de Proveedores");
        panelProveedores.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 290, 20));

        slideBar.add(panelProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 350, 40));

        panelDetalle.setBackground(new java.awt.Color(54, 70, 78));
        panelDetalle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-increase-23.png"))); // NOI18N
        panelDetalle.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 40, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Historial de Productos");
        panelDetalle.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 270, 20));

        slideBar.add(panelDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 350, 40));

        panelClasificacion.setBackground(new java.awt.Color(54, 70, 78));
        panelClasificacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-survey-23.png"))); // NOI18N
        panelClasificacion.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 40, 30));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Clasificación de Productos");
        panelClasificacion.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 270, 20));

        slideBar.add(panelClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 350, 40));

        panelListadoUsuarios.setBackground(new java.awt.Color(54, 70, 78));
        panelListadoUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-increase-23.png"))); // NOI18N
        panelListadoUsuarios.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 40, 30));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Mantenimiento de Usuarios");
        panelListadoUsuarios.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 270, 20));

        slideBar.add(panelListadoUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 350, 40));

        jPanel1.add(slideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 350, 730));

        slideIcon.setBackground(new java.awt.Color(0, 102, 204));
        slideIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slideIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-menu-30.png"))); // NOI18N
        slideIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        slideIcon.setOpaque(true);
        slideIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slideIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                slideIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                slideIconMouseExited(evt);
            }
        });
        jPanel1.add(slideIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 40, -1));

        frmCategorias.setClosable(true);
        frmCategorias.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        frmCategorias.setVisible(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnCerrarCategoria.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        btnCerrarCategoria.setText("Cerrar");
        btnCerrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarCategoriaActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jButton11.setText("Agregar Categoria");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel26.setText("Mantenimiento de Categoria");

        tablaCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id Categoria", "Nombre de Categoria"
            }
        ));
        jScrollPane4.setViewportView(tablaCategoria);

        Actualizar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(284, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(262, 262, 262)
                        .addComponent(btnCerrarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(290, 290, 290))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(459, 459, 459))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(jLabel26))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(517, Short.MAX_VALUE)
                .addComponent(Actualizar)
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrarCategoria)
                    .addComponent(jButton11))
                .addGap(87, 87, 87))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel26)
                    .addGap(38, 38, 38)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 187, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout frmCategoriasLayout = new javax.swing.GroupLayout(frmCategorias.getContentPane());
        frmCategorias.getContentPane().setLayout(frmCategoriasLayout);
        frmCategoriasLayout.setHorizontalGroup(
            frmCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmCategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        frmCategoriasLayout.setVerticalGroup(
            frmCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(frmCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 1150, 730));

        frmListadoUsuarios.setClosable(true);
        frmListadoUsuarios.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        frmListadoUsuarios.setVisible(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        btnCerrarListado.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        btnCerrarListado.setText("Cerrar");
        btnCerrarListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarListadoActionPerformed(evt);
            }
        });
        jPanel4.add(btnCerrarListado);
        btnCerrarListado.setBounds(960, 580, 120, 36);

        jTable6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre del Usuario", "DNI", "Nombre de Tipo"
            }
        ));
        jScrollPane5.setViewportView(jTable6);

        jPanel4.add(jScrollPane5);
        jScrollPane5.setBounds(240, 210, 740, 310);

        jButton7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jButton7.setText("Eliminar Usuario");
        jPanel4.add(jButton7);
        jButton7.setBounds(690, 580, 200, 36);

        jButton8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jButton8.setText("Editar Usuario");
        jPanel4.add(jButton8);
        jButton8.setBounds(420, 580, 180, 36);

        jButton9.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jButton9.setText("Agregar Usuario");
        jPanel4.add(jButton9);
        jButton9.setBounds(150, 580, 200, 36);

        jButton10.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jButton10.setText("Buscar");
        jPanel4.add(jButton10);
        jButton10.setBounds(770, 145, 100, 36);

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setText("Buscar Usuario:");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(380, 150, 120, 16);

        jLabel25.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel25.setText("Mantenimiento de Usuario");
        jPanel4.add(jLabel25);
        jLabel25.setBounds(490, 50, 330, 50);
        jPanel4.add(jTextField4);
        jTextField4.setBounds(540, 150, 190, 24);

        javax.swing.GroupLayout frmListadoUsuariosLayout = new javax.swing.GroupLayout(frmListadoUsuarios.getContentPane());
        frmListadoUsuarios.getContentPane().setLayout(frmListadoUsuariosLayout);
        frmListadoUsuariosLayout.setHorizontalGroup(
            frmListadoUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1148, Short.MAX_VALUE)
        );
        frmListadoUsuariosLayout.setVerticalGroup(
            frmListadoUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );

        jPanel1.add(frmListadoUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 1150, 730));

        frmClasificacion.setClosable(true);
        frmClasificacion.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        frmClasificacion.setVisible(true);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        btnCerrarClasificacion.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        btnCerrarClasificacion.setText("Cerrar");
        btnCerrarClasificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarClasificacionActionPerformed(evt);
            }
        });
        jPanel5.add(btnCerrarClasificacion);
        btnCerrarClasificacion.setBounds(530, 640, 100, 36);

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel21.setText("Seleccione Tipo de Producto:");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(400, 100, 210, 16);

        cbTipoProducto.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        cbTipoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTipoProducto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTipoProductoItemStateChanged(evt);
            }
        });
        jPanel5.add(cbTipoProducto);
        cbTipoProducto.setBounds(620, 90, 150, 30);

        tableClasificacionProducto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tableClasificacionProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Producto", "Nombre Producto", "Stock", "Precio/Unidad", "Fecha Ingreso", "Fecha Vencimiento", "Nombre Proveedor", "Nombre Usuario"
            }
        ));
        jScrollPane3.setViewportView(tableClasificacionProducto);

        jPanel5.add(jScrollPane3);
        jScrollPane3.setBounds(50, 160, 1060, 450);

        javax.swing.GroupLayout frmClasificacionLayout = new javax.swing.GroupLayout(frmClasificacion.getContentPane());
        frmClasificacion.getContentPane().setLayout(frmClasificacionLayout);
        frmClasificacionLayout.setHorizontalGroup(
            frmClasificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1148, Short.MAX_VALUE)
        );
        frmClasificacionLayout.setVerticalGroup(
            frmClasificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );

        jPanel1.add(frmClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 1150, 730));

        frmProductos.setClosable(true);
        frmProductos.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        frmProductos.setVisible(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        btnIngProduc.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 15)); // NOI18N
        btnIngProduc.setText("Ingresar Producto");
        btnIngProduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngProducActionPerformed(evt);
            }
        });
        jPanel2.add(btnIngProduc);
        btnIngProduc.setBounds(120, 640, 210, 32);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Buscar Producto:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(390, 110, 160, 22);

        txtBuscarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarProductoKeyTyped(evt);
            }
        });
        jPanel2.add(txtBuscarProducto);
        txtBuscarProducto.setBounds(550, 110, 200, 24);

        btnModProduc.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 15)); // NOI18N
        btnModProduc.setText("Modificar Producto");
        btnModProduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModProducActionPerformed(evt);
            }
        });
        jPanel2.add(btnModProduc);
        btnModProduc.setBounds(380, 640, 210, 32);

        btnElimProduc.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 15)); // NOI18N
        btnElimProduc.setText("Eliminar Producto");
        btnElimProduc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnElimProducMouseEntered(evt);
            }
        });
        btnElimProduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimProducActionPerformed(evt);
            }
        });
        jPanel2.add(btnElimProduc);
        btnElimProduc.setBounds(630, 640, 210, 32);

        btnCerrarRegistro.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 15)); // NOI18N
        btnCerrarRegistro.setText("Cerrar");
        btnCerrarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarRegistroActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrarRegistro);
        btnCerrarRegistro.setBounds(880, 640, 120, 32);

        tablaProducto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Producto", "Nombre Producto", "Stock", "Precio/Unidad", "Fecha Ingreso", "Fecha Vencimiento", "Nombre Proveedor", "Nombre Usuario"
            }
        ));
        TablaProducto.setViewportView(tablaProducto);

        jPanel2.add(TablaProducto);
        TablaProducto.setBounds(50, 160, 1060, 450);

        javax.swing.GroupLayout frmProductosLayout = new javax.swing.GroupLayout(frmProductos.getContentPane());
        frmProductos.getContentPane().setLayout(frmProductosLayout);
        frmProductosLayout.setHorizontalGroup(
            frmProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1150, Short.MAX_VALUE)
        );
        frmProductosLayout.setVerticalGroup(
            frmProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );

        jPanel1.add(frmProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 1150, 730));

        frmProveedores.setClosable(true);
        frmProveedores.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        frmProveedores.setVisible(true);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        btnCerrarProveedores.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        btnCerrarProveedores.setText("Cerrar");
        btnCerrarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarProveedoresActionPerformed(evt);
            }
        });
        jPanel6.add(btnCerrarProveedores);
        btnCerrarProveedores.setBounds(890, 600, 100, 36);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id Proveedores", "Nombre de Proveedores"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel6.add(jScrollPane2);
        jScrollPane2.setBounds(210, 180, 730, 340);

        jButton3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jButton3.setText("Actualizar Proveedor");
        jPanel6.add(jButton3);
        jButton3.setBounds(370, 600, 200, 36);

        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jButton1.setText("Registrar Proveedor");
        jPanel6.add(jButton1);
        jButton1.setBounds(110, 600, 200, 36);

        jButton2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jButton2.setText("Eliminar Proveedor");
        jPanel6.add(jButton2);
        jButton2.setBounds(630, 600, 200, 36);

        jButton4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jButton4.setText("Buscar");
        jPanel6.add(jButton4);
        jButton4.setBounds(710, 94, 100, 36);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel4.setText("Buscar Proveedor:");
        jPanel6.add(jLabel4);
        jLabel4.setBounds(300, 100, 127, 20);
        jPanel6.add(jTextField1);
        jTextField1.setBounds(450, 100, 240, 24);

        javax.swing.GroupLayout frmProveedoresLayout = new javax.swing.GroupLayout(frmProveedores.getContentPane());
        frmProveedores.getContentPane().setLayout(frmProveedoresLayout);
        frmProveedoresLayout.setHorizontalGroup(
            frmProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1148, Short.MAX_VALUE)
        );
        frmProveedoresLayout.setVerticalGroup(
            frmProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );

        jPanel1.add(frmProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 1150, 730));

        frmHistorial.setClosable(true);
        frmHistorial.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        frmHistorial.setVisible(true);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);

        tablaHistorialProducto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tablaHistorialProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Historial", "Fecha de Salida", "Cantidad ", "Nombre del Producto"
            }
        ));
        jScrollPane1.setViewportView(tablaHistorialProducto);

        jPanel7.add(jScrollPane1);
        jScrollPane1.setBounds(100, 130, 970, 460);

        btnCerrarHistorial.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        btnCerrarHistorial.setText("Cerrar");
        btnCerrarHistorial.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrarHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarHistorialActionPerformed(evt);
            }
        });
        jPanel7.add(btnCerrarHistorial);
        btnCerrarHistorial.setBounds(540, 620, 100, 36);

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel23.setText("Buscar Historial:");
        jPanel7.add(jLabel23);
        jLabel23.setBounds(340, 70, 120, 20);

        btnBuscarHistorial.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        btnBuscarHistorial.setText("Buscar");
        btnBuscarHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarHistorialActionPerformed(evt);
            }
        });
        jPanel7.add(btnBuscarHistorial);
        btnBuscarHistorial.setBounds(740, 65, 100, 36);
        jPanel7.add(txtidHistorial);
        txtidHistorial.setBounds(500, 70, 200, 24);

        javax.swing.GroupLayout frmHistorialLayout = new javax.swing.GroupLayout(frmHistorial.getContentPane());
        frmHistorial.getContentPane().setLayout(frmHistorialLayout);
        frmHistorialLayout.setHorizontalGroup(
            frmHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 1150, Short.MAX_VALUE)
        );
        frmHistorialLayout.setVerticalGroup(
            frmHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );

        jPanel1.add(frmHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 1150, 730));

        fontImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/FMainMenu.png"))); // NOI18N
        jPanel1.add(fontImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slideIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slideIconMouseClicked

        if (x == 350) {
            slideBar.setSize(350, 730);
            Thread th = new Thread() {
                @Override
                public void run() {
                    try {
                        int cont = 0;
                        for (int i = 350; i >= 0; i--) {
                            cont++;
                            Thread.sleep(1);
                            slideBar.setSize(i, 730);
                            try {
                                activeFrame.setSize(1150 + cont, 730);
                                activeFrame.setLocation(i, 70);
                            } catch (Exception e) {
                            }

                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };
            th.start();
            x = 0;
        } else if (x == 0) {
            slideBar.setSize(x, 730);
            Thread th = new Thread() {
                @Override
                public void run() {
                    try {
                        int cont = 0;
                        for (int i = 0; i <= x; i++) {
                            cont++;
                            Thread.sleep(1);
                            slideBar.setSize(i, 730);
                            try {
                                activeFrame.setSize((1150 + x) - cont, 730);
                                activeFrame.setLocation(i, 70);
                            } catch (Exception e) {
                            }
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };
            th.start();
            x = 350;
        }
    }//GEN-LAST:event_slideIconMouseClicked

    private void slideIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slideIconMouseEntered
        labelcolor(slideIcon);
    }//GEN-LAST:event_slideIconMouseEntered

    private void slideIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slideIconMouseExited
        resetlabelcolor(slideIcon);
    }//GEN-LAST:event_slideIconMouseExited

    private void btnCerrarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarRegistroActionPerformed
        frmProductos.setVisible(false);
    }//GEN-LAST:event_btnCerrarRegistroActionPerformed

    private void btnCerrarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarProveedoresActionPerformed
        frmProveedores.setVisible(false);
    }//GEN-LAST:event_btnCerrarProveedoresActionPerformed

    private void btnCerrarHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarHistorialActionPerformed
        frmHistorial.setVisible(false);
    }//GEN-LAST:event_btnCerrarHistorialActionPerformed

    private void btnCerrarClasificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarClasificacionActionPerformed
        frmClasificacion.setVisible(false);
    }//GEN-LAST:event_btnCerrarClasificacionActionPerformed

    private void btnCerrarListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarListadoActionPerformed
        frmListadoUsuarios.setVisible(false);
    }//GEN-LAST:event_btnCerrarListadoActionPerformed

    private void btnCerrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarCategoriaActionPerformed
        frmCategorias.setVisible(false);
    }//GEN-LAST:event_btnCerrarCategoriaActionPerformed

    private void btnElimProducMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnElimProducMouseEntered

    }//GEN-LAST:event_btnElimProducMouseEntered

    private void cbTipoProductoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoProductoItemStateChanged
        try { 
            tablaClasificacionProducto(categoriaController.getIdCategoria(cbTipoProducto.getSelectedItem().toString()));
        } catch (Exception e) {
        }

    }//GEN-LAST:event_cbTipoProductoItemStateChanged

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        dgResgistrarCategoria dg = new dgResgistrarCategoria(this, true);
        dg.setVisible(true);

    }//GEN-LAST:event_jButton11ActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        muestraCategoria();
    }//GEN-LAST:event_ActualizarActionPerformed

    private void btnBuscarHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHistorialActionPerformed
        muestraHistorialProducto(txtidHistorial.getText());
    }//GEN-LAST:event_btnBuscarHistorialActionPerformed

    private void btnIngProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngProducActionPerformed
        try {
            int f = tablaProducto.getSelectedRow();
            if (f == -1) {
                JOptionPane.showMessageDialog(null, "Por favor, seleccione un producto de la tabla");
            }
            else{
                int idProducto = (int)tablaProducto.getValueAt(f, 0);
                dgRegistarProducto.idProducto = idProducto;
                dgRegistarProducto.opcion = 2;
                dgRegistarProducto dg = new dgRegistarProducto(this, true);
                dg.getLbTitulo().setText("Ingresar Porducto");
                dg.setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hubo un error al momento de seleccionar: "+e.getMessage());
        }
    }//GEN-LAST:event_btnIngProducActionPerformed

    private void btnModProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModProducActionPerformed
            
        try {
            int f = tablaProducto.getSelectedRow();
            if (f == -1) {
                JOptionPane.showMessageDialog(null, "Por favor, seleccione un producto de la tabla");
            }
            else {
                int idProducto = (int)tablaProducto.getValueAt(f, 0);
                dgRegistarProducto.idProducto = idProducto;
                dgRegistarProducto.opcion = 1;
                dgRegistarProducto dg = new dgRegistarProducto(this, true);
                dg.getLbTitulo().setText("Modificar Porducto");
                dg.setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hubo un error al momento de seleccionar: "+e.getMessage());
        }
        
    }//GEN-LAST:event_btnModProducActionPerformed

    private void btnElimProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimProducActionPerformed
        try {
            int f = tablaProducto.getSelectedRow();
            if (f == -1) {
                JOptionPane.showMessageDialog(null, "Por favor, seleccione un producto de la tabla");
            }
            else {
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hubo un error al momento de seleccionar: "+e.getMessage());
        }
        
    }//GEN-LAST:event_btnElimProducActionPerformed

    private void txtBuscarProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarProductoKeyTyped
        tablaProductoByNombre(txtBuscarProducto.getText());
    }//GEN-LAST:event_txtBuscarProductoKeyTyped

    public void setActiveFrame(JInternalFrame frame) {
        this.activeFrame = frame;
    }

    public void llevarCbTipoProducto() {
        cbTipoProducto.removeAllItems();
        categoriaController.listadoCategoria().forEach((categoria) -> {
            cbTipoProducto.addItem(categoria.getNombre_Categoria());
        });
    }

    public void tablaClasificacionProducto(int tipo) {
        DefaultTableModel dt = (DefaultTableModel) tableClasificacionProducto.getModel();
        dt.setRowCount(0);
        productoController.listaProductoxCategoria(tipo).forEach((producto) -> {
            Object v[] = {producto.getId_producto(), producto.getNombre_producto(), producto.getStock(), producto.getPrecio(), producto.getFecha_ingreso(), producto.getFecha_vencimiento(), producto.getNombre_proveedores(), producto.getNombre()};
            dt.addRow(v);
        });
    }
    
    public void tablaProducto() {
        DefaultTableModel dt = (DefaultTableModel) tablaProducto.getModel();
        dt.setRowCount(0);
        productoController.listaProducto().forEach((producto) -> {
            Object v[] = {producto.getId_producto(), producto.getNombre_producto(), producto.getStock(), producto.getPrecio(), producto.getFecha_ingreso(), producto.getFecha_vencimiento(), producto.getNombre_proveedores(), producto.getNombre()};
            dt.addRow(v);
        });
    }
    
    public void tablaProductoByNombre(String nombre) {
        DefaultTableModel dt = (DefaultTableModel) tablaProducto.getModel();
        dt.setRowCount(0);
        productoController.listaProductoxNombre(nombre).forEach((producto) -> {
            Object v[] = {producto.getId_producto(), producto.getNombre_producto(), producto.getStock(), producto.getPrecio(), producto.getFecha_ingreso(), producto.getFecha_vencimiento(), producto.getNombre_proveedores(), producto.getNombre()};
            dt.addRow(v);
        });
    }

    public void buscarTablaClasificacionProducto(String nombre) {
        DefaultTableModel dt = (DefaultTableModel) tableClasificacionProducto.getModel();
        dt.setRowCount(0);
        productoController.listaProductoxNombre(nombre).forEach((producto) -> {
            Object v[] = {producto.getId_producto(), producto.getNombre_producto(), producto.getStock(), producto.getPrecio(), producto.getFecha_ingreso(), producto.getFecha_vencimiento(), producto.getNombre_proveedores(), producto.getNombre()};
            dt.addRow(v);
        });
    }

    public void muestraCategoria() {
        DefaultTableModel dt = (DefaultTableModel) tablaCategoria.getModel();
        dt.setRowCount(0);
        for (Categoria x : categoriaController.listadoCategoria()) {
            Object v[] = {x.getId_categoria(), x.getNombre_Categoria()};
            dt.addRow(v);
        }
    }

    public void muestraHistorialProducto(String nombre) {
        DefaultTableModel dt = (DefaultTableModel) tablaHistorialProducto.getModel();
        dt.setRowCount(0);
        for (Historial x : historialController.listadoHistorial(nombre)) {
            Object v[] = {x.getId_Historial(), x.getFecha_salida(),x.getCantidad(), x.getNombreProducto()};
            dt.addRow(v);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JScrollPane TablaProducto;
    private javax.swing.JButton btnBuscarHistorial;
    private javax.swing.JButton btnCerrarCategoria;
    private javax.swing.JButton btnCerrarClasificacion;
    private javax.swing.JButton btnCerrarHistorial;
    private javax.swing.JButton btnCerrarListado;
    private javax.swing.JButton btnCerrarProveedores;
    private javax.swing.JButton btnCerrarRegistro;
    private javax.swing.JButton btnElimProduc;
    private javax.swing.JButton btnIngProduc;
    private javax.swing.JButton btnModProduc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbTipoProducto;
    private javax.swing.JLabel fontImage;
    private javax.swing.JInternalFrame frmCategorias;
    private javax.swing.JInternalFrame frmClasificacion;
    private javax.swing.JInternalFrame frmHistorial;
    private javax.swing.JInternalFrame frmListadoUsuarios;
    private javax.swing.JInternalFrame frmProductos;
    private javax.swing.JInternalFrame frmProveedores;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel panelCategorias;
    private javax.swing.JPanel panelClasificacion;
    private javax.swing.JPanel panelDetalle;
    private javax.swing.JPanel panelListadoUsuarios;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JPanel panelProveedores;
    private javax.swing.JPanel slideBar;
    private javax.swing.JLabel slideIcon;
    private javax.swing.JTable tablaCategoria;
    private javax.swing.JTable tablaHistorialProducto;
    private javax.swing.JTable tablaProducto;
    private javax.swing.JTable tableClasificacionProducto;
    private javax.swing.JTextField txtBuscarProducto;
    private javax.swing.JTextField txtidHistorial;
    // End of variables declaration//GEN-END:variables
    private void labelcolor(JLabel label) {
        label.setBackground(new java.awt.Color(53, 162, 107));
    }

    private void resetlabelcolor(JLabel label) {
        label.setBackground(new java.awt.Color(54, 70, 78));
    }

    public javax.swing.JPanel getPanelDetalle() {
        return panelDetalle;
    }

    public javax.swing.JPanel getPanelClasificacion() {
        return panelClasificacion;
    }

    public javax.swing.JPanel getPanelListadoUsuarios() {
        return panelListadoUsuarios;
    }

    public javax.swing.JPanel getPanelProveedores() {
        return panelProveedores;
    }

    public javax.swing.JInternalFrame getFrmProveedores() {
        return frmProveedores;
    }

    public javax.swing.JInternalFrame getFrmHistorial() {
        return frmHistorial;
    }

    public javax.swing.JInternalFrame getFrmClasificacion() {
        return frmClasificacion;
    }

    public javax.swing.JInternalFrame getFrmListadoUsuarios() {
        return frmListadoUsuarios;
    }

    public javax.swing.JInternalFrame getFrmCategorias() {
        return frmCategorias;
    }

    public javax.swing.JPanel getPanelCategorias() {
        return panelCategorias;
    }

    public javax.swing.JInternalFrame getFrmProductos() {
        return frmProductos;
    }

    public javax.swing.JPanel getPanelProductos() {
        return panelProductos;
    }

}
